USE Test
DECLARE @TODAY_TIMESTAMP DATE = CURRENT_TIMESTAMP

CREATE TABLE Customer
(
	[ID] INT IDENTITY(1,1) NOT NULL,
	[NAME] VARCHAR(100) NOT NULL,
	[Latititude] DECIMAL(9,6) NULL,
	[Longtitude] DECIMAL(9,6) NULL,
CONSTRAINT [PK_Customer] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE Customer_Contacts
(
	[ID] INT IDENTITY(1,1) NOT NULL,
	[NAME] VARCHAR(100) NOT NULL,
	[Email] VARCHAR(100) NULL,
	[Contact Number] VARCHAR(12) NULL,
	[CustomerId] INT NOT NULL,
CONSTRAINT [PK_Customer_Contacts] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Customer_Contacts]  WITH CHECK ADD  CONSTRAINT [FK_CustomerId] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customer] ([ID])
GO